//https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: temporary_exposure_key_signature_list.proto

package protocols

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TEKSignatureList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Information about associated signatures.
	Signatures []*TEKSignature `protobuf:"bytes,1,rep,name=signatures" json:"signatures,omitempty"`
}

func (x *TEKSignatureList) Reset() {
	*x = TEKSignatureList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporary_exposure_key_signature_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TEKSignatureList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TEKSignatureList) ProtoMessage() {}

func (x *TEKSignatureList) ProtoReflect() protoreflect.Message {
	mi := &file_temporary_exposure_key_signature_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TEKSignatureList.ProtoReflect.Descriptor instead.
func (*TEKSignatureList) Descriptor() ([]byte, []int) {
	return file_temporary_exposure_key_signature_list_proto_rawDescGZIP(), []int{0}
}

func (x *TEKSignatureList) GetSignatures() []*TEKSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type TEKSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Information to uniquely identify the public key associated
	// with the EN server's signing key.
	SignatureInfo *SignatureInfo `protobuf:"bytes,1,opt,name=signature_info,json=signatureInfo" json:"signature_info,omitempty"`
	// Reserved for future use. Both batch_num and batch_size
	// must be set to a value of 1.
	BatchNum  *int32 `protobuf:"varint,2,opt,name=batch_num,json=batchNum" json:"batch_num,omitempty"`
	BatchSize *int32 `protobuf:"varint,3,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	// Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields).
	Signature []byte `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
}

func (x *TEKSignature) Reset() {
	*x = TEKSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temporary_exposure_key_signature_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TEKSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TEKSignature) ProtoMessage() {}

func (x *TEKSignature) ProtoReflect() protoreflect.Message {
	mi := &file_temporary_exposure_key_signature_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TEKSignature.ProtoReflect.Descriptor instead.
func (*TEKSignature) Descriptor() ([]byte, []int) {
	return file_temporary_exposure_key_signature_list_proto_rawDescGZIP(), []int{1}
}

func (x *TEKSignature) GetSignatureInfo() *SignatureInfo {
	if x != nil {
		return x.SignatureInfo
	}
	return nil
}

func (x *TEKSignature) GetBatchNum() int32 {
	if x != nil && x.BatchNum != nil {
		return *x.BatchNum
	}
	return 0
}

func (x *TEKSignature) GetBatchSize() int32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *TEKSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_temporary_exposure_key_signature_list_proto protoreflect.FileDescriptor

var file_temporary_exposure_key_signature_list_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x5f, 0x65, 0x78, 0x70, 0x6f,
	0x73, 0x75, 0x72, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x1a, 0x23, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72,
	0x61, 0x72, 0x79, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a,
	0x10, 0x54, 0x45, 0x4b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x37, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x73, 0x2e, 0x54, 0x45, 0x4b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0a,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x0c, 0x54,
	0x45, 0x4b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x73,
}

var (
	file_temporary_exposure_key_signature_list_proto_rawDescOnce sync.Once
	file_temporary_exposure_key_signature_list_proto_rawDescData = file_temporary_exposure_key_signature_list_proto_rawDesc
)

func file_temporary_exposure_key_signature_list_proto_rawDescGZIP() []byte {
	file_temporary_exposure_key_signature_list_proto_rawDescOnce.Do(func() {
		file_temporary_exposure_key_signature_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_temporary_exposure_key_signature_list_proto_rawDescData)
	})
	return file_temporary_exposure_key_signature_list_proto_rawDescData
}

var file_temporary_exposure_key_signature_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporary_exposure_key_signature_list_proto_goTypes = []interface{}{
	(*TEKSignatureList)(nil), // 0: protocols.TEKSignatureList
	(*TEKSignature)(nil),     // 1: protocols.TEKSignature
	(*SignatureInfo)(nil),    // 2: protocols.SignatureInfo
}
var file_temporary_exposure_key_signature_list_proto_depIdxs = []int32{
	1, // 0: protocols.TEKSignatureList.signatures:type_name -> protocols.TEKSignature
	2, // 1: protocols.TEKSignature.signature_info:type_name -> protocols.SignatureInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_temporary_exposure_key_signature_list_proto_init() }
func file_temporary_exposure_key_signature_list_proto_init() {
	if File_temporary_exposure_key_signature_list_proto != nil {
		return
	}
	file_temporary_exposure_key_export_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_temporary_exposure_key_signature_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TEKSignatureList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temporary_exposure_key_signature_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TEKSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_temporary_exposure_key_signature_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporary_exposure_key_signature_list_proto_goTypes,
		DependencyIndexes: file_temporary_exposure_key_signature_list_proto_depIdxs,
		MessageInfos:      file_temporary_exposure_key_signature_list_proto_msgTypes,
	}.Build()
	File_temporary_exposure_key_signature_list_proto = out.File
	file_temporary_exposure_key_signature_list_proto_rawDesc = nil
	file_temporary_exposure_key_signature_list_proto_goTypes = nil
	file_temporary_exposure_key_signature_list_proto_depIdxs = nil
}
